In [1]:
import numpy as np

print(np.__version__)

1.20.1


# I. Numpy 개요

- URL : https://numpy.org

![대체 텍스트](https://numpy.org/doc/stable/_static/numpylogo.svg)


## 1.  다차원 배열의 이해
### 1-1. 숫자 자료형

> Python 에서는 숫자형 변수로 데이터를 표현할 수 있다.\
> 예를 들어, 세 명의 학생들로 이루어진 반이 있고,\
> 이 학생들의 수학 점수를 각각의 **숫자형 변수**에 저장하는 경우 아래처럼 처리할 수 있다.

In [2]:
# 세 명의 학생들의 수학 점수
math1 = 45
math2 = 57
math3 = 63

In [11]:
# 합계와 평균 구하기

total = math1 + math2 + math3
average = total / 3

print("수학 점수의 합 : %d" % total)
print("수학 점수의 평균 : %.2f" % average)

수학 점수의 합 : 165
수학 점수의 평균 : 55.00


- 새로운 학생이 들어오면 코드를 다시 쳐야한다 <br>
➞ <font color="red">**매우 귀찮다**</font>

In [12]:
math4 = 90
total = math1 + math2 + math3 + math4
average = total / 4

print("수학 점수의 합 : %d" % total)
print("수학 점수의 평균 : %.2f" % average)

수학 점수의 합 : 255
수학 점수의 평균 : 63.75


### 1-2. 리스트 자료형

>리스트 자료형에 데이터를 저장하여 이 문제를 해결할 수 있다.\
세 명의 학생들로 이루어진 반이 있고,\
이 학생들의 수학 점수를 **리스트**에 저장하는 경우 아래와 같이 처리할 수 있다.

#### 1) 리스트를 활용하기

In [25]:
math_list = [31, 15, 92]
print(math_list)

[31, 15, 92]


In [26]:
# 평균/합 구하기

total = 0
average = 0

for math in math_list:
    total += math
average = total / len(math_list)  

print("수학 점수의 합 : %d" % total)
print("수학 점수의 평균 : %.2f" % average)


수학 점수의 합 : 138
수학 점수의 평균 : 46.00


#### 2) <span style="background-color:yellow">새로운 성적</span>을 입력하여 평균과 합 구하기

In [27]:
# 기존 리스트에 데이터 추가
math_list.append(78)

In [28]:
# 합/평균 구하는 코드는 그대로 사용 가능
total = 0
average = 0

for math in math_list:
    total += math
average = total / len(math_list)  

print("수학 점수의 합 : %d" % total)
print("수학 점수의 평균 : %.2f" % average)


수학 점수의 합 : 216
수학 점수의 평균 : 54.00


#### 3) 성적에 오류가 있어서 5점씩 올려 주어야 하는 상황
> 반복문이나 list comprehesion 사용

In [34]:
# method 1
new_ml = []
for math in math_list:
    new_ml.append(math+5)
    
print(new_ml)

[36, 20, 97, 83]


In [35]:
# method 2 : list comprehension
new_lcm = [math+5 for math in math_list]

print(new_lcm)

[36, 20, 97, 83]


#### 4) 구조 확장하기
- 1반, 2반, 3반이 있다면...

In [33]:
nested_math_score = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(nested_math_score)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


**4-1) 중첩리스트에 5점씩 올려주기**

In [36]:
nested_score2 = []

for score in nested_math_score:
    temp_list = []
    for math in score:
         temp_list.append(math+5)
    nested_score2.append(temp_list)
    
print(nested_score2)

[[16, 17, 18], [26, 27, 28], [36, 37, 38]]


<span style="color:red">**문제점**</span><br>
1. 자료구조의 중첩(차원)이 증가하면 반복문도 증가한다.
2. 코드가 갈수록 복잡해 진다.

### 1-3. Numpy로 구현한 다차원 배열 
>**NumPy**를 사용하면 중첩된 자료구조를 효율적으로 다룰 수 있다.<br>
>`import numpy as np` 형태로 사용하는게 일반적이다.

In [37]:
# Package import
import numpy as np

#### 1) ndArray 생성

In [38]:
nested_math_score = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
math_array = np.array(nested_math_score)

print(math_array)
print(type(math_array))

print(nested_math_score)
print(type(nested_math_score))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>
[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
<class 'list'>


#### 2) 각 원소에 5 더하기

In [39]:
new_ndarray = math_array+5

print(new_ndarray)

[[16 17 18]
 [26 27 28]
 [36 37 38]]


#### 3) 평균/합 구하기

In [44]:
# 전체 합/평균
sum_all = np.sum(math_array)
avg_all = np.mean(math_array)

# 반별 합/평균
sum_class = np.sum(math_array, axis=1)
avg_class = np.mean(math_array, axis=1)

print("전체 합 : %.2f" % sum_all)
print("전체 평균 : %.2f" % avg_all)
print("반별 합 : " , sum_class)
print("반별 평균 : ",  avg_class)

전체 합 : 198.00
전체 평균 : 22.00
반별 합 :  [36 66 96]
반별 평균 :  [12. 22. 32.]


## 2. NumPy의 특징

### 2-1. NumPy의 장점

> 1. 코어부분이 C로 구현되어 있어, 동일한 연산을 하더라도 Python에 비해 속도가 빠름
> 2. 라이브러리에 구현되어있는 함수들을 활용해, 짧고 간결한 코드가 작성 가능
> 3. 효율적인 메모리 사용이 가능하도록 구현되어 있음
        

#### Python의 List가 느린 이유 
>1. Python의 List는 결국 포인터 배열<br>
>2. 경우에 따라서, 객체의 메모리가 흩어져 있음 <br>
    <font color="red">캐시 활용이 어려움</font>
    
#### NumPy의 ndarray가 빠른 이유
>1. ndarray는 타입을 명시하여 원소의 배열로 데이터를 유지<br>
>2. 다차원 데이터도 연속된 메모리 공간이 할당됨<br>
>3. 많은 연산이 dimensions과 strides를 잘 활용하면 효율적으로 가능

![title](https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-02.webp)

# II. 기초
## 1. 배열생성
### 1-1. array()를 이용한 방법
>가장 기본적인 방법은, `array()` 함수를 이용하여 일반적인 Python List, tuple에서 배열을 만드는 것 이다

In [45]:
import numpy as np

In [47]:
# Python List를 활용하여 NumPy 배열 만들기
data = [0, 1, 2, 3, 4, 5]

a = np.array(data)
print(a, type(a))

[0 1 2 3 4 5] <class 'numpy.ndarray'>


#### 1) number
> `number` 데이터를 사용하여 다차원 배열을 생성\
> 정수형(`int`), 실수형(`float`), 복소수형(`complex`), 부호없는 정수형(`uint`)

In [54]:
# 부호 비트 있음
iarr = np.array([[1, 2], [3, 4]])
iarr

array([[1, 2],
       [3, 4]])

In [53]:
# 부호 비트 없음
uarr = np.array([[1, 2], [3, 4]], dtype='uint')
uarr

array([[1, 2],
       [3, 4]], dtype=uint32)

#### 2) 실수형 
> 실수형의 default data type 은 float64

In [57]:
farr = np.array([[1. ,2], [3.14, 4.73]])
print(farr, farr.dtype)

[[1.   2.  ]
 [3.14 4.73]] float64


#### 3) Boolean

In [60]:
barr = np.array([True, False, True, False])
print(barr, barr.dtype)

[ True False  True False] bool


#### 4) 형변환

In [66]:
temp = np.array(['1', '20', 300, 4000], np.float64)
print("np.float64 : ", temp, type(temp), type(temp[0]), sep='\t')

temp = np.array(['1', '20', 300, 4000], float)
print("float : ", temp, type(temp), type(temp[0]), sep='\t')

temp = np.array(['1', '20', 300, 4000], int)
print("int \t: ", temp, '', type(temp), type(temp[0]), sep='\t')

temp = np.array(['1', '20', 300, 4000], np.float32)
print("np.float32 : ", temp, type(temp), type(temp[0]), sep='\t')

np.float64 : 	[1.e+00 2.e+01 3.e+02 4.e+03]	<class 'numpy.ndarray'>	<class 'numpy.float64'>
float : 	[1.e+00 2.e+01 3.e+02 4.e+03]	<class 'numpy.ndarray'>	<class 'numpy.float64'>
int 	: 	[   1   20  300 4000]		<class 'numpy.ndarray'>	<class 'numpy.int32'>
np.float32 : 	[1.e+00 2.e+01 3.e+02 4.e+03]	<class 'numpy.ndarray'>	<class 'numpy.float32'>


In [71]:
data = [1, 2, 3, 4]

a = np.array(data)
a[3] = -9

b = a
b[3] = 314
print(a) # a도 변해 버린것을 확인 가능 

c = np.array(a, copy=True) # Deep Copy
c[3] = -100

print("a : ", a)
print("b : ", b)
print("c : ", c)

[  1   2   3 314]
a :  [  1   2   3 314]
b :  [  1   2   3 314]
c :  [   1    2    3 -100]


### 1-2. arange() 를 사용하는 방법
> 일련의 숫자를 만들기 위해, NumPy는 Python의 `range`내장 함수와 유사한 함수, `arange`함수를 제공한다\
> default value : start = 0, step = 1

In [72]:
import numpy as np

a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [73]:
b = np.arange(5, 37, 5)
print(b)

[ 5 10 15 20 25 30 35]


In [75]:
c = np.arange(0)
c

array([], dtype=int32)

In [76]:
d = np.array([])
d

array([], dtype=float64)